### ISSUE TITLE
US 3 - Location history endpoint

### ISSUE THREAD

**Issue by abengl** [abengl/Fleet-Management-API#1]
- [x] abengl/Fleet-Management-API#2

- [x] abengl/Fleet-Management-API#3

- [x] abengl/Fleet-Management-API#4
